stages:
  - build
  - test
  - deploy

first job:
  image:
    name: alpine/k8s:1.20.7
  stage: test
  tags:
    - default
  script:
    - mkdir -p ~/.kube
    - cp $kubeconfig ~/.kube/config
    - kubectl get ns
    - kubectl config set-context --current --namespace=david-seyder
    - kubectl apply -f server/kubernetes/

docker-build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  before_script:
  - mkdir -p /kaniko/.docker
  - cp ${docker_credentials} /kaniko/.docker/config.json
  tags: 
    - default
  script:
    - > 
      /kaniko/executor \
        --context $CI_PROJECT_DIR/server/ \
        --dockerfile $CI_PROJECT_DIR/server/Dockerfile \
        --destination davman808/glassdragon-nodeserver:${CI_COMMIT_SHORT_SHA} \
        --use-new-run=true;
