image:
  name: alpine/k8s:1.20.7

stages:
  - build
  - test
  - deploy

variables:
  # disable Docker TLS validation
  DOCKER_TLS_CERTDIR: ""
  # localhost address is shared by both the job container and the dind container (as they share the same Pod)
  # So this configuration make the dind service as our Docker daemon when running Docker commands
  DOCKER_HOST: "tcp://localhost:2375"

first job:
  stage: test
  tags:
    - default
  script:
    - mkdir -p ~/.kube
    - cp $kubeconfig ~/.kube/config
    - kubectl get ns
    - kubectl config set-context --current --namespace=david-seyder
    - kubectl apply -f server/kubernetes/

services:
  - docker:stable-dind

docker-build:
  image: docker:stable
  stage: build
  tags: 
    - default
  script:
      - docker build -t hello .
      - docker tag my-registry/hello:${CI_COMMIT_SHORT_SHA}
      - docker push my-registry/hello:${CI_COMMIT_SHORT_SHA}
