image:
  name: alpine/k8s:1.20.7

stages:
  - test

first job:
  stage: test
  tags:
    - default
  script:
    - mkdir -p ~/.kube
    - cp $kubeconfig ~/.kube/config
    - kubectl get ns
    - kubectl config set-context --current --namespace=david-seyder
    - kubectl apply -f server/kubernetes/
